name: storage with dns failover
on:
  workflow_call:
    inputs:
      storage_account_resource_group_name:
        required: true
        type: string
      private_storage_account_names: 
        type: string
        required: true
      sku:
        required: true
        type: string  
      primary_subscription_Id:
        required: true
        type: string
      private_dns_zone_resource_group_name:
        required: true
        type: string
      storage_account_private_dns_zone_group_name:
        required: true
        type: string
      storage_account_private_dns_zone_name:
        required: true
        type: string
      secondary_private_endpoint_resource_group_name:
        required: true
        type: string
      secondary_private_endpoint_subscription_Id:
        required: true
        type: string
      secondary_private_endpoint_name:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS_DELOITTE_SUB:
        required: true
jobs:  
  job1:
    permissions:
      contents: none
    runs-on: ubuntu-latest       
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: SNawazmac/storage_account_failover
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_DELOITTE_SUB}}
        enable-AzPSSession: true   
    - name: Invoke storage failover and set GRS
      uses: azure/powershell@v1
      with:
        inlineScript: |
         ./Invoke_Failover_Storage_multi-values_param.ps1 -storage_account_resource_group_name "${{inputs.storage_account_resource_group_name}}" -private_storage_account_names "${{inputs.private_storage_account_names}}" -sku "${{inputs.sku}}"  
        azPSVersion: "latest"
      
    - name: Link PE to Private DNS Zone
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Link_Multi_PEs_to_DNS_Zone.ps1 -primary_subscription_Id "${{ inputs.primary_subscription_Id }}" -private_dns_zone_resource_group_name "${{ inputs.private_dns_zone_resource_group_name }}" -storage_account_private_dns_zone_group_name "${{ inputs.storage_account_private_dns_zone_group_name}} -storage_account_private_dns_zone_name "${{ inputs.storage_account_private_dns_zone_name }} -secondary_private_endpoint_resource_group_name "${{ inputs.secondary_private_endpoint_resource_group_name }} -secondary_private_endpoint_subscription_Id "${{inputs.secondary_private_endpoint_subscription_Id}} -secondary_private_endpoint_name "${{inputs.secondary_private_endpoint_name}}
        azPSVersion: "latest"
